### ISSUE TITLE
Random encounter generator window closes when clicking on any button

### ISSUE THREAD

**Issue by nolorfin** [etriebe/dnd-randomizer#71]
This is what the console says:

vTools failed to load source map: Could not load content for https://localhost/modules/dnd-randomizer/scripts/lib/gridjs.umd.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**Comment by nolorfin** [comment]
It seems to be an incompatibility with the JB2A module.

**Comment by nolorfin** [comment]
![image](https://github.com/etriebe/dnd-randomizer/assets/72673748/80019744-f20d-47ac-beca-8d5f2c381703)

**Comment by nolorfin** [comment]
I've been told on the JB2A community that the errors refer to this mod's code itself. The fact is that both mods used to work together until a few days ago.

**Comment by etriebe** [comment]
I'll take a look when I get a chance! Thanks for the report!

**Comment by etriebe** [comment]
Ah, this is just due to source mapping. It's just a warning that is only applicable for debugging that code, which no one would need to do for this module. I'm going to won't fix based on that. It might be possible to fix but I think the impact is purely just a warning. Shouldn't cause issues for anyone.
